name: Etsy Promotion Code

on:
  workflow_dispatch:  # Allow manual trigger

jobs:
  scan-codes:
    runs-on: windows-latest
    strategy:
      matrix:
        test-file: ['git_sele1.py', 'git_sele2.py', 'git_sele3.py', 'git_sele4.py']
        include:
          - test-file: 'git_sele1.py'
            results-file: 'results1.json'
          - test-file: 'git_sele2.py'
            results-file: 'results2.json'
          - test-file: 'git_sele3.py'
            results-file: 'results3.json'
          - test-file: 'git_sele4.py'
            results-file: 'results4.json'
      fail-fast: false  # Continue with other jobs even if one fails
    
    steps:
    - uses: actions/checkout@v3
    - uses: browser-actions/setup-chrome@v1
      with: 
        chrome-version: 132
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U selenium
        pip install webdriver-manager
        
    - name: Run scanner - ${{ matrix.test-file }}
      run: python ${{ matrix.test-file }}
        
    - name: Upload Results - ${{ matrix.test-file }}
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: scan-results-${{ matrix.test-file }}-${{ github.run_number }}
        path: |
          ${{ matrix.results-file }}
          promotion_results.txt
        retention-days: 90

  combine-results:
    needs: scan-codes
    runs-on: ubuntu-latest
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v3
      
    - name: Upload Combined Results
      uses: actions/upload-artifact@v3
      with:
        name: all-scan-results-${{ github.run_number }}
        path: |
          scan-results-*
        retention-days: 90
